dist: trusty
sudo: false

language: node_js
node_js:
  - '14'

env:
  global:
    - COVERALLS_PARALLEL=true

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - npm install -g yarn

install:
  - yarn

script:
  - yarn test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

